description: 'Gemma3 Testing'

# Python function as a provider for response
providers:
  - id: 'file://google_gemma_3_research.py'

prompts:
  - 'When was google.com launched?'

# Set properties for all tests
defaultTest:
  options:
    provider:
      text:
        id: huggingface:text-generation:google/gemma-3-270m-it

# Test Case
tests:
  - description: 'Test if output meets our expected answer'
    assert:
      - type: icontains-any 
        value: 'Google.com was launched on **May 15, 2003**. '

